In [2]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install transformers

Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


In [5]:
import torch
from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification

In [6]:
import math

In [7]:
import pandas as pd
import plotly.express as px
import numpy as np

In [8]:
from scipy.special import softmax

In [9]:
MODEL = f"cardiffnlp/twitter-roberta-base-sentiment"


In [10]:
tokenizer = AutoTokenizer.from_pretrained(MODEL)

In [11]:
model = AutoModelForSequenceClassification.from_pretrained(MODEL)

In [17]:
def normalize(score, alpha=15):
    """
    Normalize the score to be between -1 and 1 using an alpha that
    approximates the max expected value
    """
    norm_score = score/math.sqrt((score*score) + alpha)
    return norm_score

In [23]:
def polarity_scores_roberta(example):
    encoded_text = tokenizer(example, return_tensors='pt')
    output = model(**encoded_text)
    scores = output[0][0].detach().numpy()
    scores = softmax(scores)
    print(scores)
    total = scores[0]*-1 + scores[1] + scores[2]
    print(total)
    print(normalize(total))
    return normalize(total)


In [24]:
bitcoin_news = pd.read_csv('bitcoin_news_2022.csv')

In [25]:
bitcoin_news["sentiment2"] = bitcoin_news["sentiment"]


In [26]:
polarity_scores_roberta(bitcoin_news["healine"][0])

[0.02668336 0.796488   0.17682865]
0.9466332755982876
0.23743037286860103


0.23743037286860103

In [27]:
vader_neg=[]
vader_neu=[]
vader_pos=[]

In [28]:
for i in range(0, len(bitcoin_news)):
    vader_neg.append(polarity_scores_roberta(bitcoin_news["healine"][i]))
    


[0.02668336 0.796488   0.17682865]
0.9466332755982876
0.23743037286860103
[0.00322191 0.6174052  0.37937284]
0.993556106230244
0.24848880136013016
[0.01353379 0.86036295 0.12610321]
0.9729323610663414
0.24364002434734505
[0.00724834 0.8968408  0.095911  ]
0.9855034681968391
0.24659777322209608
[0.04159305 0.9209553  0.0374517 ]
0.9168139472603798
0.23035418836402896
[0.05846324 0.8486479  0.09288884]
0.8830734938383102
0.2223032660691781
[0.00738567 0.9216081  0.0710062 ]
0.9852286214008927
0.24653318014625605
[0.49896598 0.48468807 0.01634595]
0.002068042755126953
0.000533966267201199
[0.03303174 0.9233671  0.04360105]
0.9339364022016525
0.23442192650777716
[0.00586437 0.65058136 0.3435541 ]
0.9882711018435657
0.24724802493344297
[0.02373973 0.9252956  0.05096471]
0.9525205697864294
0.23882302205197317
[0.2507838  0.7270784  0.02213774]
0.4984323177486658
0.12764198825139886
[0.10435191 0.8070086  0.08863941]
0.791296124458313
0.20017648103749366
[0.03874179 0.8696053  0.09165281]
0.9

[0.02099832 0.4359234  0.5430783 ]
0.9580033775418997
0.24011866560359404
[0.00949753 0.6358407  0.35466176]
0.9810049505904317
0.245540142000266
[0.5351696  0.44450644 0.02032403]
-0.07033913768827915
-0.018158492808609667
[0.08881183 0.8772381  0.03394999]
0.8223762586712837
0.20770585717018836
[0.0059397  0.87932837 0.11473174]
0.9881204147823155
0.24721262980453024
[0.01264001 0.62850773 0.35885227]
0.9747199928388
0.24406103801324522
[0.00627725 0.887833   0.10588977]
0.9874455230310559
0.24705409124287805
[0.00465657 0.9033211  0.09202234]
0.9906868580728769
0.2478153306494837
[0.01126434 0.7914222  0.1973134 ]
0.9774712435901165
0.24470872856142073
[0.00661498 0.8129333  0.1804515 ]
0.9867698424495757
0.24689534750048883
[0.00330216 0.314897   0.6818009 ]
0.9933957431931049
0.24845117040018813
[0.04856751 0.824422   0.12701046]
0.9028649590909481
0.22703140276907544
[0.01831815 0.92115796 0.0605238 ]
0.9633636064827442
0.24138410326257942
[0.00562432 0.7275742  0.26680145]
0.988

KeyboardInterrupt: 

In [19]:
bitcoin_news

year  month  day  year_month  year_month_day  \
0      2022      1    1      202201        20220101   
1      2022      1    1      202201        20220101   
2      2022      1    1      202201        20220101   
3      2022      1    1      202201        20220101   
4      2022      1    1      202201        20220101   
...     ...    ...  ...         ...             ...   
13439  2022      8   31      202208        20220831   
13440  2022      8   31      202208        20220831   
13441  2022      8   31      202208        20220831   
13442  2022      8   31      202208        20220831   
13443  2022      8   31      202208        20220831   

                                                 healine  \
0      Bitcoin starts 2022 at $47.2K as fresh researc...   
1      The year for Bitcoin: A 2021 roundup of the fl...   
2      El Salvador President Nayib Bukele Predicts Tw...   
3      Mexico Announces It Will Issue Its Own Digital...   
4      Kevin O'Leary Reveals Crypto Strategy, Why He ...   
...                                                  ...   
13439  Bitcoin Price Chart May Signal End to Selloff,...   
13440  Crypto will become an inflation hedge — just n...   
13441  Singapore Considers Stricter Rules for Retail ...   
13442  Pimride (PIM) Is Now Available for Trading on ...   
13443  What You Need to Know About Running a Cryptocu...   

                                                    link  sentiment  \
0      https://cointelegraph.com/news/bitcoin-starts-...     0.3182   
1      https://cointelegraph.com/news/the-year-for-bi...     0.1027   
2      https://www.nasdaq.com/articles/el-salvador-pr...     0.1280   
3      https://news.bitcoin.com/mexico-announces-it-w...     0.0000   
4      https://news.bitcoin.com/kevin-oleary-crypto-s...     0.0000   
...                                                  ...        ...   
13439  https://www.inferse.com/197765/bitcoin-price-c...     0.0000   
13440  https://techbullion.com/crypto-will-become-an-...     0.0000   
13441  https://www.inferse.com/197692/singapore-consi...     0.0000   
13442  https://www.livebitcoinnews.com/pimride-pim-is...     0.0000   
13443  https://www.imcgrupo.com/what-you-need-to-know...     0.0000   

       sentiment2  
0        0.237430  
1        0.248489  
2        0.243640  
3        0.246598  
4        0.230354  
...           ...  
13439    0.233234  
13440    0.166321  
13441   -0.025340  
13442    0.248100  
13443    0.196895  

[13444 rows x 9 columns]